spring.application.name=email
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/ms-email
spring.datasource.username=postgres
spring.datasource.password=2803
spring.jpa.hibernate.ddl-auto=update

## Configurações RabbitMQ
spring.rabbitmq.addresses=amqps://iefthocf:v6vgXS9-5Ek-jZogC2MloL7KF6ZId56W@duck.lmq.cloudamqp.com/iefthocf
broker.queue.email.name=default.mail
